# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: submission.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from snapshotter.utils.models.proto.snapshot_submission import submission_pb2 as submission_pb2


class SubmissionBase(abc.ABC):

    @abc.abstractmethod
    async def SubmitSnapshotSimulation(self, stream: 'grpclib.server.Stream[submission_pb2.SnapshotSubmission, submission_pb2.SubmissionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def SubmitSnapshot(self, stream: 'grpclib.server.Stream[submission_pb2.SnapshotSubmission, submission_pb2.SubmissionResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/submission.Submission/SubmitSnapshotSimulation': grpclib.const.Handler(
                self.SubmitSnapshotSimulation,
                grpclib.const.Cardinality.STREAM_UNARY,
                submission_pb2.SnapshotSubmission,
                submission_pb2.SubmissionResponse,
            ),
            '/submission.Submission/SubmitSnapshot': grpclib.const.Handler(
                self.SubmitSnapshot,
                grpclib.const.Cardinality.UNARY_UNARY,
                submission_pb2.SnapshotSubmission,
                submission_pb2.SubmissionResponse,
            ),
        }


class SubmissionStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SubmitSnapshotSimulation = grpclib.client.StreamUnaryMethod(
            channel,
            '/submission.Submission/SubmitSnapshotSimulation',
            submission_pb2.SnapshotSubmission,
            submission_pb2.SubmissionResponse,
        )
        self.SubmitSnapshot = grpclib.client.UnaryUnaryMethod(
            channel,
            '/submission.Submission/SubmitSnapshot',
            submission_pb2.SnapshotSubmission,
            submission_pb2.SubmissionResponse,
        )
