# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: submission.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'submission.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10submission.proto\x12\nsubmission\"d\n\x07Request\x12\x0e\n\x06slotId\x18\x01 \x01(\x04\x12\x10\n\x08\x64\x65\x61\x64line\x18\x02 \x01(\x04\x12\x13\n\x0bsnapshotCid\x18\x03 \x01(\t\x12\x0f\n\x07\x65pochId\x18\x04 \x01(\x04\x12\x11\n\tprojectId\x18\x05 \x01(\t\"q\n\x12SnapshotSubmission\x12$\n\x07request\x18\x01 \x01(\x0b\x32\x13.submission.Request\x12\x11\n\tsignature\x18\x02 \x01(\t\x12\x0e\n\x06header\x18\x03 \x01(\t\x12\x12\n\ndataMarket\x18\x04 \x01(\t\"%\n\x12SubmissionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbc\x01\n\nSubmission\x12\\\n\x18SubmitSnapshotSimulation\x12\x1e.submission.SnapshotSubmission\x1a\x1e.submission.SubmissionResponse(\x01\x12P\n\x0eSubmitSnapshot\x12\x1e.submission.SnapshotSubmission\x1a\x1e.submission.SubmissionResponseB1Z/github.com/PowerLoom/proto-snapshot-server/pkgsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'submission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/PowerLoom/proto-snapshot-server/pkgs'
  _globals['_REQUEST']._serialized_start=32
  _globals['_REQUEST']._serialized_end=132
  _globals['_SNAPSHOTSUBMISSION']._serialized_start=134
  _globals['_SNAPSHOTSUBMISSION']._serialized_end=247
  _globals['_SUBMISSIONRESPONSE']._serialized_start=249
  _globals['_SUBMISSIONRESPONSE']._serialized_end=286
  _globals['_SUBMISSION']._serialized_start=289
  _globals['_SUBMISSION']._serialized_end=477
# @@protoc_insertion_point(module_scope)
