services:
  snapshotter-lite-local-collector:
    image: ghcr.io/powerloom/snapshotter-lite-local-collector:latest
    container_name: snapshotter-lite-local-collector-${FULL_NAMESPACE}
    profiles: ["local-collector"]
    expose:
      - ${LOCAL_COLLECTOR_PORT}
    ports:
      - ${LOCAL_COLLECTOR_PORT}:${LOCAL_COLLECTOR_PORT}
    volumes:
      - ./shared-volume:/keys
    environment:
      - SIGNER_ACCOUNT_ADDRESS=$SIGNER_ACCOUNT_ADDRESS
      - SIGNER_ACCOUNT_PRIVATE_KEY=$SIGNER_ACCOUNT_PRIVATE_KEY
      - IPFS_URL=$IPFS_URL
      - IPFS_API_KEY=$IPFS_API_KEY
      - IPFS_API_SECRET=$IPFS_API_SECRET
      - PROTOCOL_STATE_CONTRACT=$PROTOCOL_STATE_CONTRACT
      - DATA_MARKET_CONTRACT=$DATA_MARKET_CONTRACT
      - PROST_RPC_URL=$PROST_RPC_URL
      - PROST_CHAIN_ID=$PROST_CHAIN_ID
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - LOCAL_COLLECTOR_PORT=$LOCAL_COLLECTOR_PORT
      - RELAYER_PRIVATE_KEY=$RELAYER_PRIVATE_KEY
      - BLOCK_TIME=$BLOCK_TIME
      - MAX_STREAM_POOL_SIZE=$MAX_STREAM_POOL_SIZE
      - STREAM_HEALTH_CHECK_TIMEOUT_MS=$STREAM_HEALTH_CHECK_TIMEOUT_MS
      - STREAM_WRITE_TIMEOUT_MS=$STREAM_WRITE_TIMEOUT_MS
      - MAX_WRITE_RETRIES=$MAX_WRITE_RETRIES
      - MAX_CONCURRENT_WRITES=$MAX_CONCURRENT_WRITES
      - DATA_MARKET_IN_REQUEST=$DATA_MARKET_IN_REQUEST
    networks:
      - custom_network
    restart: on-failure:10
  snapshotter-lite-v2:
    image: snapshotter-lite-v2
    container_name: snapshotter-lite-v2-${SLOT_ID}-${FULL_NAMESPACE}
    volumes:
      - ./logs-${FULL_NAMESPACE_LOWER}:/app/logs
    environment:
      - SIGNER_ACCOUNT_ADDRESS=$SIGNER_ACCOUNT_ADDRESS
      - SIGNER_ACCOUNT_PRIVATE_KEY=$SIGNER_ACCOUNT_PRIVATE_KEY
      - FULL_NAMESPACE=$FULL_NAMESPACE
      - SLOT_ID=$SLOT_ID
      - SOURCE_RPC_URL=$SOURCE_RPC_URL
      - PROST_RPC_URL=$PROST_RPC_URL
      - IPFS_URL=$IPFS_URL
      - IPFS_API_KEY=$IPFS_API_KEY
      - IPFS_API_SECRET=$IPFS_API_SECRET
      - PROTOCOL_STATE_CONTRACT=$PROTOCOL_STATE_CONTRACT
      - DATA_MARKET_CONTRACT=$DATA_MARKET_CONTRACT
      - LOCAL_COLLECTOR_PORT=$LOCAL_COLLECTOR_PORT
      - SLACK_REPORTING_URL=$SLACK_REPORTING_URL
      - POWERLOOM_REPORTING_URL=$POWERLOOM_REPORTING_URL
      - WEB3_STORAGE_TOKEN=$WEB3_STORAGE_TOKEN
      - NAMESPACE=$NAMESPACE
      - TELEGRAM_REPORTING_URL=$TELEGRAM_REPORTING_URL
      - TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
      - SNAPSHOT_CONFIG_REPO=$SNAPSHOT_CONFIG_REPO
      - SNAPSHOT_CONFIG_REPO_BRANCH=$SNAPSHOT_CONFIG_REPO_BRANCH
      - SNAPSHOTTER_COMPUTE_REPO=$SNAPSHOTTER_COMPUTE_REPO
      - SNAPSHOTTER_COMPUTE_REPO_BRANCH=$SNAPSHOTTER_COMPUTE_REPO_BRANCH
      - CRON_RESTART=$CRON_RESTART
    command: >
      bash -c "
        rm -f /app/last_successful_submission.txt;
        trap 'rm -f /app/last_successful_submission.txt' SIGTERM;
        bash init_docker.sh;
      "
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - custom_network
    restart: on-failure:10
networks:
  custom_network:
    name: ${DOCKER_NETWORK_NAME}
    driver: bridge
    external: true
