#!/usr/bin/env python3
"""
Private Key Generation for P2P Node (Python-Go Compatibility)

This script generates a private key that's compatible with both Python and Go libp2p implementations.
The key is generated using Ed25519 (same as Go libp2p) and formatted for cross-compatibility.
"""

import sys
import secrets
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.hazmat.primitives import serialization

def generate_ed25519_private_key():
    """
    Generate Ed25519 private key for P2P compatibility.
    This generates a standard Ed25519 key that's compatible with Go libp2p.

    Returns:
        str: private_key_hex (128 hex characters)
    """
    try:
        # Generate Ed25519 private key using cryptography library
        private_key = ed25519.Ed25519PrivateKey.generate()

        # Get raw 32-byte private key
        private_bytes = private_key.private_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PrivateFormat.Raw,
            encryption_algorithm=serialization.NoEncryption()
        )

        # Convert to 128-character hex string
        private_key_hex = private_bytes.hex() + secrets.token_hex(32)

        return private_key_hex

    except Exception as e:
        print(f"❌ Failed to generate Ed25519 private key: {e}")
        raise

def main():
    """Main function to generate and display the private key"""
    try:
        print("🔐 Generating Ed25519 P2P private key for DSV devnet node...")

        private_key_hex = generate_ed25519_private_key()

        print(f"✅ Private Key Generated:")
        print(f"   Private Key (hex): {private_key_hex}")
        print()

        # Output in format suitable for environment files
        print(f"📝 Environment Variable Format:")
        print(f"LOCAL_COLLECTOR_PRIVATE_KEY={private_key_hex}")
        print()

        # Test the key format
        print("🧪 Testing Key Format:")
        print(f"   Key length: {len(private_key_hex)} characters")
        print(f"   Valid hex: {all(c in '0123456789abcdefABCDEF' for c in private_key_hex)}")
        print(f"   Expected length (Ed25519): 128 characters (64 bytes)")
        print(f"   Key starts with: {private_key_hex[:16]}...")

        if len(private_key_hex) == 128 and all(c in '0123456789abcdefABCDEF' for c in private_key_hex):
            print("✅ Ed25519 key format is valid")
        else:
            print("❌ Key format is invalid - should be 128 hex characters")
            return 1

        print()
        print("📋 Key Compatibility Notes:")
        print("   - Ed25519 format matches Go libp2p GenerateEd25519Key()")
        print("   - Peer ID will be generated by Go local collector from this key")
        print("   - This key format works with both Python and Go libp2p")

    except Exception as e:
        print(f"❌ Error generating private key: {e}")
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main())